name = "cf-demo-worker"
main = "src/worker.js"
compatibility_date = "2025-08-26"
account_id = "125b8c582db7b7f2079a38dabfc9cfb3"

[vars]
ENV = "dev"
MY_SECRET = "dev-secret"

[env.preview]
name = "cf-demo-worker-preview"   # 👈 give preview its own name
workers_dev = true
[env.preview.vars]
ENV = "preview"
MY_SECRET = "preview-secret"

[env.production]
name = "cf-demo-worker"           # 👈 keep production as the base name
routes = ["example.com/*"]        # replace later with your domain
[env.production.vars]
ENV = "production"
MY_SECRET = "production-secret"
